version: '3'

services:
  client:
    restart: always
    image: yp-client:0.1
    build:
      context: ./client
    volumes:
      - ./client:/client

  server:
    restart: always
    image: yp-server:0.1
    build:
      context: ./server
    volumes:
      - ./server:/server

  # db:
  #   restart: always
  #   image: yp-db:0.1
  #   build:
  #     context: ./db
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - ./db/MYSQL_ROOT_PASSWORD:/run/secrets/MYSQL_ROOT_PASSWORD
  #   environment:
  #     - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
  #     - MYSQL_DATABASE=ypdb

  nginx:
    depends_on:
      - client
      - server
    restart: always
    image: nginx:alpine
    container_name: nginx
    ports:
      - 3000:3000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

