version: '3'

services:
  server:
    image: server:0.8
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./server:/server
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/server/gcp_key.json
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /server/connect_proxy.sh
        /server/start_server.sh
