version: '3'

services:
  client:
    restart: always
    image: yp-client:0.1
    build:
      context: ./client
    volumes:
      - ./client:/client

  server:
    depends_on:
      - db
    restart: always
    image: yp-server:0.1
    build:
      context: ./server
    volumes:
      - ./server:/server

  db:
    restart: always
    image: yp-db:0.1
    build:
      context: ./db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/MYSQL_ROOT_PASSWORD:/run/secrets/MYSQL_ROOT_PASSWORD
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=ypdb

  nginx:
    depends_on:
      - client
      - server
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # react:
  #   image: client:0.2
  #   container_name: client
  #   restart: always
  #   volumes:
  #     - ./client:/client
  #   entrypoint: ["/bin/sh", "-c"]
  #   command:
  #     - |
  #       /client/start_client.sh 

  # express:
  #   image: server:0.8
  #   container_name: server
  #   restart: always
  #   volumes:
  #     - ./server:/server
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/server/gcp_key.json
  #   entrypoint: ["/bin/sh", "-c"]
  #   command:
  #     - |
  #       /server/connect_proxy.sh 
  #       sleep 5s
  #       /server/start_server.sh
